server:
  port: 8761

spring:
  application:
    name: spring-cloud-euraka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
  instance:
    hostname: 127.0.0.1
